# @format

version: '3'
services:
  plasmid:
    image: ghcr.io/ultirts/ts-plasmid:nightly
    pull_policy: always
    ports:
      - '8081:8081'
    environment:
      - PLASMID_DB_HOST=mysql
      - PLASMID_DB_USER=chan
      - PLASMID_DB_PASSWORD=Diy.2002
      - PLASMID_DB_NAME=plasmid
      - PLASMID_REDIS_HOST=redis
      - PLASMID_REDIS_PORT=6379
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: [CMD, wget, http://localhost:8081, -O, /dev/null]
      timeout: 3s
      retries: 10
  autohost:
    image: ghcr.io/ultirts/ts-autohost:nightly
    pull_policy: always
    ports:
      - '3000-3005:3000-3005'
      - '7000-7005:7000-7005'
      - '3000-3005:3000-3005/udp'
      - '7000-7005:7000-7005/udp'
      - '5000:5000'
    environment:
      - PLASMID_SERVER_HOST=plasmid
      - PLASMID_SERVER_PORT=5000
    depends_on:
      plasmid:
        condition: service_healthy
    volumes:
      - ./maps:/autohost/engine/maps
      - ./games:/autohost/engine/games
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=plasmid
      - MYSQL_USER=chan
      - MYSQL_PASSWORD=Diy.2002
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h localhost -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      timeout: 20s
      retries: 10
  redis:
    image: redis:3.2
    ports:
      - '6379:6379'
    healthcheck:
      test: [CMD, redis-cli, ping]
      timeout: 20s
      retries: 10
